### ISSUE TITLE
graphiql.html TemplateDoesNotExist at /graphiql

### ISSUE THREAD

**Issue by ajayk800** [lmcgartland/graphene-file-upload#1]
> 
> Request Method: | GET
> -- | --
> http://127.0.0.1:8000/graphiql
> 2.0.2
> TemplateDoesNotExist
> graphiql.html
> 
>

**Comment by lmcgartland** [comment]
Thanks for finding this! Will remove that line, I used a custom template to support JWT authentication.

**Comment by lmcgartland** [comment]
@ajayk800 should be fixed now in 0.1.1
