### ISSUE TITLE
How to handle multiple files?

### ISSUE THREAD

**Issue by mattdamon108** [lmcgartland/graphene-file-upload#11]
Thank you for your wonderful package. I love it.

I'm trying to implement file upload into my django project. I've found that multiple file can be handled by apollo-upload-client, but I couldn't find whether it is possible to be handled by server side with graphene-file-upload in documentation.

Can you advise me of how to handle multiple files with graphene-file-upload?

**Comment by reaganscofield** [comment]
@mattdamon108  can u please help me how you implementing it because nothing is working with me 
am actually getting an None when i am trying to print the file.
```python
import graphene
from graphene_file_upload.scalars import Upload

class CreateProfile(graphene.Mutation):
    id = graphene.UUID()
    agentProfile = Upload(required=True)

   class Arguments:
        agentProfile = Upload(required=True)
        agentFirstName = graphene.String()

   @classmethod
    def mutate(self, file, info, **kwargs):
          agentProfile = kwargs.get('agentProfile') #info.context.FILES
          agentFirstName =  kwargs.get('agentFirstName')

         print(kwargs)    #if i print the dict i can see a file in the dict but its a string not
                                   #the actually file

          print(info.context.FILES.get(file))  #i print its output "None"

```

please i need your help because i have been trying over and over again nothing is working with me

**Comment by reaganscofield** [comment]
which version of django are you using ?

**Comment by reaganscofield** [comment]
still getting None value, can u please share your client query with me may be the problem is coming from client

**Comment by mattdamon108** [comment]
@reaganscofield I'm using Django==2.0.7

please refer to the below;

```
mutation postNew($title: String, $content: String, $files: Upload) {
    cudNoticeboard(title: $title, content: $content, files: $files) {
      noticeboard {
        id
        user {
          id
          fullname
        }
        title
        content
        firstDate
        views
        likes {
          id
        }
        noticeboardimages {
          id
          image
        }
      }
    }
  }
```

**Comment by reaganscofield** [comment]
everything look the same but i don't why i am still getting None value instead of file value!

if your print your 'uploaded_file'  value? 
and what version of graphene are you using?

sorry for some many questions

**Comment by mattdamon108** [comment]
@lmcgartland I've solved multiple files problem with your example code in testsite. I think current version 1.0.0 is much simple and concise to handle single file and mutiple file with same code in django. Thank you for your good package.

**Comment by gj1118** [comment]
@mattdamon108 - can you please post how you are uploading from the UI ? I have indeed setup the backend using graphene , and it works when I am using insomnia , but it does not work from the UI. I am pretty sure that I am doing something wrong here and any help will be well appreciated. 

Thanks

**Comment by mattdamon108** [comment]
@gj1118 Man, I hope this can help you to fix your problem.

```
// input tag to get a file from DOM

<input
  type="file"
  name="image"
  onChange={({
    target: {
      validity,
      files: [file]
    }
  }) =>
    validity.valid &&
    this.setState({
      image: [file]
    })
  }
  className="mr-1"
/>
```

```
// Schema

export const NEW_POST_NOTICE = gql`
  mutation postNew(
    $title: String
    $content: String
    $onNotice: Boolean
    $files: Upload
  ) {
    cudNoticeboard(
      title: $title
      content: $content
      onNotice: $onNotice
      files: $files
    ) {
      noticeboard {
        id
        user {
          id
          fullname
        }
        title
        content
        firstDate
        views
        likes {
          id
        }
        onNotice
        noticeboardimages {
          id
          image
        }
      }
    }
  }
`;
```

```
// Mutation part

<Mutation
  mutation={NEW_POST_NOTICE}
  variables={{
    title: this.state.title,
    content: draftToHtml(
      convertToRaw(this.state.content.getCurrentContent())
    ),
    files:
      this.state.image.length > 0
        ? this.state.image
        : null,
    onNotice: this.state.onNotice
  }}
  onCompleted={ ... }
  update={ ... }
...
/>
```

**Comment by w4ugit** [comment]
I use graphene-file-upload on the backend, and my frontend is an application on ReactNative. There is no way I can transfer the files to save them. Can someone share the working code?
