### ISSUE TITLE
Run query from Postman

### ISSUE THREAD

**Issue by StefanoSega** [lmcgartland/graphene-file-upload#18]
Hi guys.
First of all, congrats for this very useful lib.

I wrote a very basic mutation for file upload:
```
class TestMutation(graphene.Mutation):
    class Arguments:
        sql_file = Upload()

    Output = OperationStatusRetType

    def mutate(self, info, sql_file_ref):
            sql_file = info.context.FILES.get(sql_file_ref)
            sql_query_template = sql_file.read().decode('utf-8')
            sql_file_names = sql_file.names
            in_memory_file = io.StringIO(sql_query_template)
            put_s3_object(s3, AWS_DEFAULT_S3_BUCKET, in_memory_file.getvalue(), sql_file_names.split('/')[-1])

        return AddDatasetRetType(sqlFilePath=sql_file_names.split('/')[-1],
                                 operationStatus=OperationStatusRetType(success=True))
```

and I consume it this way:
```
mutation Test {
  testMutation(sql_file: "test.png") {
    success
    error
  }
}
```

I would like to test it with Postman, posting the file using the POST form-data option, like in the pic:

![image](https://user-images.githubusercontent.com/8436281/47631781-d57ecb00-db60-11e8-97f5-d15432a7587b.png)

but I get the error "Must provide query string" as generally in GraphQL the querystring should be in the form body.

In the headers "Content-Type" is "application/graphql".

Do you know how I can test my GraphQL endpoint using Postman?
Also is still not clear to me if I need to assign a value to the Upload field ("sql_file" in this case) or it can be left empty.

Thanks

**Comment by davidroeca** [comment]
Hi @StefanoSega,

Is there a way of changing "Content-Type" to "multipart/form-upload"? That should hopefully solve the issue. Alternatively, it might be worth a try from another tool such as insomnia. #7 has some additional discussion around that.

Also, I'd recommend checking out the django example https://github.com/lmcgartland/graphene-file-upload/blob/master/examples/django/testsite/schema.py

**Comment by gj1118** [comment]
Hi @StefanoSega /@DavidRoeca , I am getting the same error. I am using Insomnia . Here is how it looks
![image](https://user-images.githubusercontent.com/473101/62817624-a2ae2e00-bb07-11e9-83a8-87bfc8c9edb4.png)

My upload mutation is copied verbatim from the one mentioned in the readme of this project. 
Can you please help me out with this ? 

Thanks

**Comment by davidroeca** [comment]
@gj1118 looks like you put the `operations` field in the name section of the file. If we're following the example verbatim in insomnia, you'll need to do a multipart post with 3 parameters:
1. A field named `operations` with the value `{"query": "mutation ($file: Upload) { myUpload(fileIn: $file) { ok }}", "variables": { "file": null }}`
2. A field named `map` with the value `{ "0": ["variables.file"]}`
3. A file field named `0` with the file you're uploading set as the value

**Comment by gj1118** [comment]
@davidroeca thank you Sir, for taking time out for me. Much appreciated. Would it be possible for you to create a small video tutorial and post it on youtube ?  You see, I am not that smart and need a little bit extra. 

Thank you once again for all of your time and patience.

**Comment by davidroeca** [comment]
In your picture, look at the bottom left where it says `name` and `value`—that’s where you put the name/value of each field I mentioned, insomnia should work out of the box if you just fill that out as a multipart request

**Comment by gj1118** [comment]
Thanks ,I got it working :) Your instructions were easy to understand. Apologies for being stupid. 

![image](https://user-images.githubusercontent.com/473101/62818176-b8c0ec00-bb11-11e9-8dba-c1cb0b39090b.png)

**Comment by davidroeca** [comment]
Glad to help! It’s not a simple implementation, confusion with file uploads in graphql is a rite of passage at this point. I think we can close this issue, anyone stuck can try following the above steps first

**Comment by gj1118** [comment]
Sorry, Just one more question please - if you may. I am trying to pass a second parameter as an input. This is for the postid. I need to update the location of the column of the post model about the location of this image. 

Here is what I have 
```Python
class UploadMutation(graphene.Mutation):
    class Arguments:
        file = Upload(required=True)
        postid = graphene.ID(required=True, description="Global ID of the post")


    success = graphene.Boolean()

    def mutate(self, info, file,postid, **kwargs):
        # do something with your file
        print(type(file))
        print(filepath)
        print(postid)
        if(not os.path.exists(filepath)):
            os.makedirs(filepath)
        completeFileInfo = os.path.join(filepath,file.filename)
        # post = db_session.query(ModelPost).filter_by(id=postid).first()
        file.save(completeFileInfo)
        # post.headerimage= completeFileInfo
        # post.update()
        # db_session.commit()

        return UploadMutation(success=True)
```
and these are how I am sending parameters 
1. `{"query": "mutation ($file: Upload!, $postid: ID!) { uploadFile(file: $file, postid:$postid) { success }}", "variables": { "file": null, "postid":null }}`
2. `{ "0": ["variables.file"],"1": ["variables.postid"] }`

![image](https://user-images.githubusercontent.com/473101/62818417-0c810480-bb15-11e9-8cf4-8f8ba4263888.png)

But I am getting this error 

`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/flask_graphql/graphqlview.py", line 68, in dispatch_request
    data = self.parse_body()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/graphene_file_upload/flask/__init__.py", line 21, in parse_body
    request.files
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/graphene_file_upload/utils.py", line 22, in place_files_in_operations
    file_obj = files[key]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/werkzeug/datastructures.py", line 431, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.HTTPException.wrap.<locals>.newcls: 400 Bad Request: KeyError: '1'`

Can you please suggest what I am doing wrong here ? 

Thanks once again for all your help.

**Comment by davidroeca** [comment]
1 will need to be a file too, it can’t just be text. Check out [the multipart request spec](https://github.com/jaydenseric/graphql-multipart-request-spec/blob/master/readme.md#multipart-form-field-structure) for more info on the structure

**Comment by gj1118** [comment]
Sure, I will read up on that. But if that is the case, how can I pass in the postid , so that I can update the post with the location of the image that I have uploaded. Please suggest. 


thanks

**Comment by davidroeca** [comment]
Ah sorry, didn’t read the entire thing. Since postid is a string, you’ll need to change the postid variable in the operations from null to the string you want, and you can remove all references to “1”

**Comment by gj1118** [comment]
You , Sir are a champ and Godsend!! It worked !!! Thanks for all the help and have a good night ! I will let you enjoy without being a disturbance going forward today. 

thanks for all the help.
