### ISSUE TITLE
from graphene_file_upload.flask import FileUploadGraphQLView fails with this error:

### ISSUE THREAD

**Issue by mfix22** [lmcgartland/graphene-file-upload#21]
```
Traceback (most recent call last):
  File "server.py", line 4, in <module>
    import graphene_file_upload.flask
  File "~/.local/share/virtualenvs/backend-JODmqDQ7/lib/python2.7/site-packages/graphene_file_upload/flask.py", line 1, in <module>
    from flask import request
ImportError: cannot import name request
```

Potentially I am just using this incorrectly?

**Comment by davidroeca** [comment]
Yeah just pip install the github url

**Comment by mfix22** [comment]
Like `pipenv install https://github.com/lmcgartland/graphene-file-upload`?

**Comment by davidroeca** [comment]
@mfix22 I created a PR for this precise issue in #22 I think it was just an honest oversight.

On a completely different note, I'd recommend checking out [poetry](https://github.com/sdispater/poetry) when you have the chance.

**Comment by davidroeca** [comment]
@mfix22 1.1.0 should be up on PYPI--please close if you're able to install the fix

**Comment by mfix22** [comment]
Thanks! I updated to 1.1.0, and I am getting this error:
```shell
Traceback (most recent call last):
  File "server.py", line 19, in <module>
    from graphene_file_upload.flask import FileUploadGraphQLView
ImportError: No module named flask
```

**Comment by davidroeca** [comment]
Opened #23, which should likely fix it. Confirmed that distribution breaks the package on `python2` without a specific distribution fix
