### ISSUE TITLE
Port this package to Flask

### ISSUE THREAD

**Issue by hxuanhung** [lmcgartland/graphene-file-upload#3]
Hi, I've ported this package successfully to Flask and I want to create a PR for it. 

Particularly, I make two changes: 
- `from graphene_django.views import GraphQLView` to `from flask_graphql import GraphQLView`
- and `request_type = request.META.get("CONTENT_TYPE")` to `request_type = request.mimetype`

It's not clear for me to make this works for both Flask and Django. Do you have any idea?

**Comment by lmcgartland** [comment]
I think the best thing might be to have to modules exported from this package, a view for Django and one for Flask. They can share the underlying logic. File a pull request just so I can take a look and we can work together on getting it merged.
