### ISSUE TITLE
cannot import name Field

### ISSUE THREAD

**Issue by sodrooome** [lmcgartland/graphene-file-upload#33]
Hello, I found a little problem but I don't know what caused it, when I want to try making a file upload an error appears like this :

`ImportError: cannot import name 'Field'`

I try to follow the provided example, but still give me the same results, can anyone help?

**Comment by davidroeca** [comment]
@sodrooome which example--flask or django? A brief `grep` of this repo indicates no import of `Field`. I believe the problem may exist externally.

**Comment by sodrooome** [comment]
I'm sorry, it turns out I'm the one who's made the mistake. I was not quite right when specify the `schema` in my `settings` , so it seems like the mistake was there. the problem now is resolved

thank you for the respond.

**Comment by davidroeca** [comment]
Sounds good, glad to hear you figured it out
