### ISSUE TITLE
Testing file upload API

### ISSUE THREAD

**Issue by FerCalatayud** [lmcgartland/graphene-file-upload#38]
Hi, I already implemented the package in my schema, but I haven't found a tool to test this API.

I already use postman and graphiql with other queries and mutations but haven't found a way to test image uploads.

any thoughts?

**Comment by FerCalatayud** [comment]
UPDATE:

I use a software for graphql api testing named Altair https://altair.sirmuel.design/

It is great and easy to use. To test image upload see this article:

https://sirmuel.design/working-with-file-uploads-using-altair-graphql-d2f86dc8261f

**Comment by imolorhe** [comment]
Hey @FerCalatayud, how did you find out about Altair?

**Comment by imolorhe** [comment]
@lmcgartland Perhaps you can recommend Altair as a tool for testing this implementation to help others as well?

**Comment by imolorhe** [comment]
Oh wait, looks like the package isn't maintained anymore 😕

**Comment by FerCalatayud** [comment]
> Hey @FerCalatayud, how did you find out about Altair?

hmm, I think,  just by googling.

**Comment by FerCalatayud** [comment]
> Oh wait, looks like the package isn't maintained anymore 😕

But it is, though. The last edit was only 3 days ago. It is an overwhelmingly big improvement from just testing with graphiql.

I think it is the best tool out there. Maybe when Postman handles of the Graphql features I switch, but for now, Postman is not good for Graphql

**Comment by FerCalatayud** [comment]
> Oh wait, looks like the package isn't maintained anymore 😕

You mean, this package?

If so, yes, I think so too, do you know any other currently maintained package for Graphql file upload?

**Comment by fkromer** [comment]
@imolorhe Thanks a lot for Altair! It's great!
