### ISSUE TITLE
No need for redundant dependencies

### ISSUE THREAD

**Issue by begimai** [lmcgartland/graphene-file-upload#39]
I want to use it for my Django project, why it creates extra dependencies? Why do I need flask?

```
[package.extras]
all = ["Flask (>=1.0.2)", "graphene (>=2.1.2)", "Flask-Graphql (>=2.0.0)", "graphene-django (>=2.0.0)"]
django = ["graphene-django (>=2.0.0)"]
flask = ["Flask (>=1.0.2)", "graphene (>=2.1.2)", "Flask-Graphql (>=2.0.0)"]
```

**Comment by davidroeca** [comment]
Simply install with `pip install graphene_file_upload[django]` or without [extras](https://packaging.python.org/tutorials/installing-packages/#installing-setuptools-extras). This is a convenience. By default, neither flask nor Django is installed

**Comment by begimai** [comment]
Great, thank you!
