### ISSUE TITLE
Generate a new release

### ISSUE THREAD

**Issue by jackton1** [lmcgartland/graphene-file-upload#52]
@lmcgartland Is it possible to get a new version deployed to PyPI ??

Thanks

**Comment by lmcgartland** [comment]
Yes-thinking about bumping to 1.3, does that sound good?

**Comment by jackton1** [comment]
Yes it does. Thanks

**Comment by lmcgartland** [comment]
Released https://pypi.org/project/graphene-file-upload/1.3.0/

**Comment by lmcgartland** [comment]
Thanks for all your work @jackton1 ! Really appreciate it. Let me know if you have any issues with the released package.

**Comment by jackton1** [comment]
Thanks @lmcgartland
